### PR TITLE
Unique-login-page folder added

### PR DESCRIPTION
**Pull request by Akanksha7-art**

### CODE REVIEW

**Review by dikshantmali — APPROVED** [review]

**Comment by Akanksha7-art** [comment]
Thank you

**Review by MallikarjunHt — COMMENTED** [review]
Just A image with password and loging field with background image
Screenshot from 2020-10-08 10-17-05

**Comment by Akanksha7-art** [comment]
@MallikarjunHt  ya, so?.....what are you tring to say, I didn't get you sir

**Comment by MallikarjunHt** [comment]
well you could change the background on clicking enter or even say a message using alert, by adding sinple html and css you will not explore new concepts. try to include some js or just CSS tricks to make it more intresting. @Akanksha7-art  just adding my opinion :smiley: dont be :worried: lets learn to gether.

**Comment by Akanksha7-art** [comment]
@MallikarjunHt  I totally agree to you sir, but I am a complete beginner right now. I am trying this for the first .  I'll keep in mind  your opinion in my further PR's  . Thank You

**Pull request merged**
