### PR TITLE
Presentation of Dropdown navigation using HTML and CSS

### PR DESCRIPTION
**Pull request by suubh**

### CODE REVIEW

**Review by dikshantmali — APPROVED** [review]

**Comment by dikshantmali** [comment]
@suubh awesome work :)

**Comment by suubh** [comment]
@dikshantmali Thanks . Will it be merged ?

**Comment by dikshantmali** [comment]
@suubh sure it will definitely get merged. I am not merging it today because if I merge it today your cthis contribution will not count in hacktoberfest. If you havent register for hacktoberfest then go and register and get limited edition free t-shirt on your 4 pull request made in october.

**Comment by suubh** [comment]
Cool . I have registered . 
Thanks @dikshantmali

**Comment by suubh** [comment]
You said u will merge tomorrow .

**Pull request merged**
