### PR TITLE
ParallaxScrolling

### PR DESCRIPTION
**Pull request by alkatrivedi**
Illustration of Parallax Scrolling using HTML and CSS. Thank you:)

### CODE REVIEW

**Comment by dikshantmali** [comment]
@alkatrivedi Great work :) Really loved it. I will merge it tomorrow so that it can count in your hactoberfest contribution.

**Review by dikshantmali — APPROVED** [review]

**Comment by alkatrivedi** [comment]
Thank you so much:)

**Comment by alkatrivedi** [comment]
@dikshantmali Thank you for merging my pull request. Just wanted to ask can I make another PR tomorrow for Hacktoberfest contribution?

**Comment by alkatrivedi** [comment]
@dikshantmali Can I add one more page with different idea?

**Pull request merged**
