### PR TITLE
Added HTML and CSS based website about myself

### PR DESCRIPTION
**Pull request by hmmonotone**
Have a look here : https://hmmonotone.github.io/cv/

### CODE REVIEW

**Comment by dikshantmali** [comment]
So I can use your details like name personal interest etc. ok, I am merging it good work.

**Comment by dikshantmali** [comment]
@hmmonotone is it looking this way as shown below. The one I have seen at https://hmmonotone.github.io/portfolio/ is better. Please made one more PR with improved UI. Thanks
df

**Comment by hmmonotone** [comment]
Actually this only the HTML and I have one more file with a better ui see: https://hmmonotone.github.io/portfolio/

**Comment by hmmonotone** [comment]
@dikshantmali

**Pull request merged**
