### PR TITLE
Added Birthday Website

### PR DESCRIPTION
**Pull request by vrindajadwani**

### CODE REVIEW

**Review by MallikarjunHt — APPROVED** [review]
Good one. Please try to fix the cards layout bracks at certain width. :+1:

**Comment by vrindajadwani** [comment]
Hi,
Thanks for replying. I think my website's layout does not look proper on
100% zoom, it looks good on 80%. Also, it is not compatible with mobiles,
so kindly view it on a desktop/ laptop. This was just a beginner project. I
hope you'll approve my request :-)

Regards,
Vrinda Jadwani

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MallikarjunHt** [comment]
Nothing to worry. We all learn to gether, try using css grid property/ bootstrap is also good. You can improve the design. 😄

**Comment by vrindajadwani** [comment]
Thank you for the suggestions! I'll try to improve.

Regards,
Vrinda Jadwani

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request merged**
